Repository Codeit-Sprint-Teamproject/frontend, pull requests merged in 2024-11, with the labels that each got.

#9 "Husky를 이용한 Eslint, Prettier, pre-commit 검사 추가
  .husky/pre-commit
  package-lock.json
  package.json
Labels: 기능 🔧, 최적화 🌠

#10 Update package.json
  package.json
Labels: 기능 🔧, 최적화 🌠

#12 chore: auto-merge 병합조건 수정
  .github/workflows/auto-merge.yml
Labels: 오류 수정 ✔️, 최적화 🌠

#19 Feat/mypage 커스텀 모달 레이아웃 구현
  app/layout.tsx
  app/mypage/_components/Profile.tsx
  app/mypage/_components/ProfileModifyForm.tsx
  app/mypage/_svg/CloseBtn.tsx
  app/mypage/_svg/ImageIcon.tsx
  app/mypage/page.tsx
  components/Modal.tsx
  components/ModalPortal.tsx
  store/modal.ts
Labels: 기능 🔧, 디자인 🎨
