Repository Codeit-Sprint-Teamproject/frontend, pull requests merged in 2024-12, with the labels that each got.

#22 Feat/mypage 마이페이지 와이어프레임 기반 스타일 적용
  .prettierignore
  app/globals.css
  app/mypage/_components/NavigationCard.tsx
  app/mypage/_components/Profile.tsx
  app/mypage/_components/ProfileModifyForm.tsx
  app/mypage/_components/Sidebar.tsx
  app/mypage/_lib/profile.ts
  app/mypage/_lib/profileSchema.ts
  app/mypage/_svg/ImageIcon.tsx
  app/mypage/bookmark/page.tsx
  app/mypage/layout.tsx
  app/mypage/meetings/page.tsx
  app/mypage/page.tsx
  app/mypage/reviews/page.tsx
  next.config.js
  package-lock.json
  package.json
Labels: 기능 🔧, 디자인 🎨

#24 Feat/signuppage 회원가입 페이지 기능 및 유효성 검사 구현
  app/auth/signup/_components/form-button.tsx
  app/auth/signup/_components/form-input.tsx
  app/auth/signup/_components/form.tsx
  app/auth/signup/_lib/signup.ts
  app/auth/signup/_lib/validation.ts
  app/auth/signup/page.tsx
  app/globals.css
  components.json
  components/ui/button.tsx
  components/ui/input.tsx
  lib/utils.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: 기능 🔧

#25 feat/meetings-list 모임 목록 페이지 UI 구현
  .gitignore
  app/_components/CustomCalendar.css
  app/_components/MainPageBody.tsx
  app/_components/MainPageHeader.tsx
  app/meeting-detail/[meetingsId]/page.tsx
  app/page.tsx
  app/utils/dateFormatter.ts
  app/utils/validation.ts
  package-lock.json
  package.json
Labels: 디자인 🎨

#28 Style/reading calendar 나의 독서 달력 초기 스타일 적용
  .github/workflows/auto-merge.yml
  .gitignore
  app/_components/CustomCalendar.css
  app/_components/MainPageBody.tsx
  app/_components/MainPageHeader.tsx
  app/auth/signup/_components/form-button.tsx
  app/auth/signup/_components/form-input.tsx
  app/auth/signup/_components/form.tsx
  app/auth/signup/_lib/signup.ts
  app/auth/signup/_lib/validation.ts
  app/auth/signup/page.tsx
  app/globals.css
  app/meeting-detail/[meetingsId]/page.tsx
  app/mypage/_components/CustomReadingCalendar.css
  app/mypage/_components/MyReadingCalendar.tsx
  app/mypage/_components/NavigationCard.tsx
  app/mypage/page.tsx
  app/page.tsx
  app/utils/dateFormatter.ts
  app/utils/validation.ts
  components.json
  components/ui/button.tsx
  components/ui/input.tsx
  lib/utils.ts
  next.config.js
  package-lock.json
  package.json
  tailwind.config.ts
Labels: 디자인 🎨

#31 Style/reading calendar 독서 달력 스타일 수정
  app/mypage/_components/CustomReadingCalendar.css
  app/mypage/_components/MyReadingCalendar.tsx
  app/mypage/_svg/NextIcon.tsx
  app/mypage/_svg/PrevIcon.tsx
Labels: 기능 🔧, 디자인 🎨, 리팩토링 ⚙️

#32 재활용도와 코드를 간략하게 작성을 위한 api 유틸 fetchAPI 그리고 로그인이 안된 상황에서 mypage에 접근했을시 login으로 redirect 시켜주는 middleware파일 추가
  app/auth/signup/_components/form.tsx
  app/auth/signup/_lib/signup.ts
  lib/fetchAPI.ts
  middleware.ts
  package-lock.json
  package.json
Labels: 기능 🔧

#34 feat/mainpage-body-function 모임목록페이지 기능구현
  app/_components/CirclueProgressBar.tsx
  app/_components/CustomCalendar.css
  app/_components/CustomDropdown.tsx
  app/_components/Main.tsx
  app/_components/MainPageBody.tsx
  app/_components/MainPageHeader.tsx
  app/utils/Img.tsx
  components/ui/dropdown-menu.tsx
  components/ui/label.tsx
  components/ui/switch.tsx
  package-lock.json
  package.json
  public/calendarIcon.tsx
  public/dropdownIcon.tsx
  public/heart.png
Labels: 기능 🔧, 디자인 🎨

#35 Feat/mypage-layout2 나의 모임 페이지 와이어프레임 기반 스타일 적용
  app/mypage/_components/MyReadingCalendar.tsx
  app/mypage/_components/Sidebar.tsx
  app/mypage/_svg/Calendar.tsx
  app/mypage/_svg/Users.tsx
  app/mypage/bookmark/page.tsx
  app/mypage/layout.tsx
  app/mypage/meetings/_components/Meeting.tsx
  app/mypage/meetings/_components/Meetings.tsx
  app/mypage/meetings/_components/Tab.tsx
  app/mypage/meetings/_components/TabContext.tsx
  app/mypage/meetings/page.tsx
  app/mypage/page.tsx
  app/mypage/reviews/page.tsx
  types/meeting.ts
Labels: 기능 🔧, 디자인 🎨, 리팩토링 ⚙️

#36 Feat/loginpage-fetchAPI 클라이언트 와 서버 환경에서 쿠키토큰 받아오는 방법 세분화
  lib/fetchAPI.ts
Labels: 기능 🔧, 최적화 🌠

#37 Feat/loginpage-loginpage 로그인 페이지 기능 구현 및 회원가입 페이지와의 공용 컴포넌트 생성
  app/auth/_components/form-button.tsx
  app/auth/_components/form-input-field.tsx
  app/auth/_svg/EyeIcon.tsx
  app/auth/_utils/cookie.ts
  app/auth/login/_components/login-form-input.tsx
  app/auth/login/_components/login-form.tsx
  app/auth/login/_lib/login-validation.ts
  app/auth/login/_lib/login.ts
  app/auth/login/page.tsx
  app/auth/signup/_components/form-input.tsx
  app/auth/signup/_components/form.tsx
Labels: 기능 🔧, 리팩토링 ⚙️

#38 Feat/loginpage-signuppagerefactor 회원가입 페이지 로그인 페이지 기능에 맞추어 리팩토링 및 기능추가 (#18)
  app/auth/signup/_components/signup-form-input.tsx
  app/auth/signup/_components/signup-form.tsx
  app/auth/signup/_lib/signup-validation.ts
  app/auth/signup/_lib/signup.ts
  app/auth/signup/page.tsx
Labels: 기능 🔧, 리팩토링 ⚙️

#39 Feat/loginpage 로그인 페이지, 회원가입 페이지, fetchAPI 기능 구현 및 리팩토링
  app/auth/_components/form-button.tsx
  app/auth/_components/form-input-field.tsx
  app/auth/_svg/EyeIcon.tsx
  app/auth/_utils/cookie.ts
  app/auth/login/_components/login-form-input.tsx
  app/auth/login/_components/login-form.tsx
  app/auth/login/_lib/login-validation.ts
  app/auth/login/_lib/login.ts
  app/auth/login/page.tsx
  app/auth/signup/_components/form-input.tsx
  app/auth/signup/_components/signup-form-input.tsx
  app/auth/signup/_components/signup-form.tsx
  app/auth/signup/_lib/signup-validation.ts
  app/auth/signup/_lib/signup.ts
  app/auth/signup/page.tsx
  lib/fetchAPI.ts
Labels: 기능 🔧, 리팩토링 ⚙️

#46 Feat,refactor/signup,login signup 로그인 페이지 기능 구현 및 회원가입 페이지 유효성 및 중복 검증 기능 추가
  app/auth/_components/form-button.tsx
  app/auth/_components/form-input-field.tsx
  app/auth/_svg/EyeIcon.tsx
  app/auth/login/_components/login-form-input.tsx
  app/auth/login/_components/login-form.tsx
  app/auth/login/_lib/login-validation.ts
  app/auth/login/_lib/login.ts
  app/auth/signup/_components/signup-form-duplicateCheckButton.tsx
  app/auth/signup/_components/signup-form-input.tsx
  app/auth/signup/_components/signup-form.tsx
  app/auth/signup/_lib/duplicate-check.ts
  app/auth/signup/_lib/signup-validation.ts
  app/auth/signup/_lib/signup.ts
  lib/fetchAPI.client.ts
  lib/fetchAPI.server.ts
Labels: 기능 🔧, 리팩토링 ⚙️, 최적화 🌠

#47 Feat,refactor/signup,login 로그인페이지 회원가입 페이지 기능추가 및 리팩토링
  app/auth/_components/form-button.tsx
  app/auth/_components/form-input-field.tsx
  app/auth/_svg/EyeIcon.tsx
  app/auth/login/_components/login-form-input.tsx
  app/auth/login/_components/login-form.tsx
  app/auth/login/_lib/login-validation.ts
  app/auth/login/_lib/login.ts
  app/auth/signup/_components/signup-form-duplicateCheckButton.tsx
  app/auth/signup/_components/signup-form-input.tsx
  app/auth/signup/_components/signup-form.tsx
  app/auth/signup/_lib/duplicate-check.ts
  app/auth/signup/_lib/signup-validation.ts
  app/auth/signup/_lib/signup.ts
  lib/fetchAPI.client.ts
  lib/fetchAPI.server.ts
Labels: 기능 🔧, 최적화 🌠

#48 style/meeting-detial-ui 모임 상세페이지 UI 개발
  app/meeting-detail/[meetingsId]/_components/BookInfo.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailLeft.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailRight.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailTabs.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingInfo.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingReviews.tsx
  app/meeting-detail/[meetingsId]/page.tsx
  components/ui/progress.tsx
  package-lock.json
  package.json
  public/Avatar.tsx
  public/BookIcon.tsx
  public/BookOpenIcon.tsx
  public/CalendarDotIcon.tsx
  public/ChevronDownIcon.tsx
  public/HeartIcon.tsx
  public/ShareIcon.tsx
  public/StarBlank.tsx
  public/StarFill.tsx
  public/UserIcon.tsx
  public/UsersIcon.tsx
  public/calendar-dot.png
  public/dropdownIcon.tsx
  public/heart.png
Labels: 디자인 🎨

#49 Feat/mypage-profile-mock 비밀번호 수정 시 비밀번호 확인 유효성 검사 추가
  app/_utils/Img.tsx
  app/_utils/dateFormatter.ts
  app/_utils/validation.ts
  app/globals.css
  app/mypage/_components/MyMeetingList.tsx
  app/mypage/_components/MyReadingCalendar.tsx
  app/mypage/_components/Profile.tsx
  app/mypage/_components/ProfileModifyForm.tsx
  app/mypage/_lib/profile.ts
  app/mypage/_lib/profileSchema.ts
  app/mypage/_svg/EditIcon.tsx
  app/mypage/_svg/ImageIcon.tsx
  app/mypage/_svg/MoreIcon.tsx
  app/mypage/page.tsx
  mocks/data/user/meetingList.json
  mocks/data/user/readingList.json
  mocks/data/user/user.json
  mocks/handlers/user/profile.ts
  package-lock.json
  package.json
  public/book.png
  types/book.ts
  types/meeting.ts
  types/user.ts
Labels: 기능 🔧, 디자인 🎨, 리팩토링 ⚙️

#51 Style/signup 회원가입 페이지 UI 변경
  app/auth/_components/form-button.tsx
  app/auth/_components/form-input-field.tsx
  app/auth/_svg/CheckIcon.tsx
  app/auth/_svg/EyeIcon.tsx
  app/auth/signup/_components/TermsAgreement.tsx
  app/auth/signup/_components/signup-form-duplicateCheckButton.tsx
  app/auth/signup/_components/signup-form-input.tsx
  app/auth/signup/_components/signup-form.tsx
  app/auth/signup/page.tsx
  app/globals.css
  components/ui/checkbox.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: 기능 🔧, 디자인 🎨

#52 Feat/mypage-profile-mock 마이페이지 모임 컨테이너 swiper 버튼 커스텀
  app/globals.css
  app/mypage/_components/MyMeetingList.tsx
  app/mypage/_components/Profile.tsx
  app/mypage/_components/ProfileModifyForm.tsx
  hooks/userProfileQuery.ts
  mocks/data/user/meetingList.json
  mocks/handlers/user/profile.ts
Labels: 기능 🔧, 디자인 🎨, 리팩토링 ⚙️

#53 Feat/mypage 마이페이지 작업 완료
  app/_utils/Img.tsx
  app/_utils/dateFormatter.ts
  app/_utils/validation.ts
  app/globals.css
  app/mypage/_components/CustomReadingCalendar.css
  app/mypage/_components/MyMeetingList.tsx
  app/mypage/_components/MyReadingCalendar.tsx
  app/mypage/_components/NavigationCard.tsx
  app/mypage/_components/Profile.tsx
  app/mypage/_components/ProfileModifyForm.tsx
  app/mypage/_components/Sidebar.tsx
  app/mypage/_lib/profile.ts
  app/mypage/_lib/profileSchema.ts
  app/mypage/_svg/Calendar.tsx
  app/mypage/_svg/EditIcon.tsx
  app/mypage/_svg/ImageIcon.tsx
  app/mypage/_svg/MoreIcon.tsx
  app/mypage/_svg/NextIcon.tsx
  app/mypage/_svg/PrevIcon.tsx
  app/mypage/_svg/Users.tsx
  app/mypage/bookmark/page.tsx
  app/mypage/layout.tsx
  app/mypage/meetings/_components/Meeting.tsx
  app/mypage/meetings/_components/Meetings.tsx
  app/mypage/meetings/_components/Tab.tsx
  app/mypage/meetings/_components/TabContext.tsx
  app/mypage/meetings/page.tsx
  app/mypage/page.tsx
  app/mypage/reviews/page.tsx
  hooks/userProfileQuery.ts
  mocks/data/user/meetingList.json
  mocks/data/user/readingList.json
  mocks/data/user/user.json
  mocks/handlers/user/profile.ts
  next.config.js
  package-lock.json
  package.json
  public/book.png
  types/book.ts
  types/meeting.ts
  types/user.ts
Labels: 기능 🔧, 디자인 🎨, 리팩토링 ⚙️

#60 Feat/my-meetings/active-done 참여 중인 모임과 완료한 모임 불러오기
  app/mypage/_components/MyMeetingList.tsx
  app/mypage/meetings/_components/Meeting.tsx
  app/mypage/meetings/_components/MeetingList.tsx
  app/mypage/meetings/_components/Meetings.tsx
  app/mypage/meetings/_components/Pagination.tsx
  app/mypage/meetings/_components/Tab.tsx
  app/mypage/meetings/_lib/mymeetings.ts
  app/mypage/meetings/_svg/PageNext.tsx
  app/mypage/meetings/_svg/PagePrev.tsx
  app/mypage/meetings/page.tsx
  mocks/data/user/meetingList.json
  next.config.js
  types/meeting.ts
Labels: 기능 🔧, 디자인 🎨, 오류 수정 ✔️

#61 Feat/my-meetings/created-bookmark 만든 모임과 찜한 모임 조회하기
  app/mypage/meetings/_components/Meeting.tsx
  app/mypage/meetings/_components/MeetingList.tsx
  app/mypage/meetings/_lib/mymeetings.ts
  app/mypage/meetings/_svg/Heart.tsx
  hooks/useMyMeetingCountQuery.ts
  hooks/useMyMeetingQuery.ts
Labels: 기능 🔧, 리팩토링 ⚙️

#62 Feat/meeting detail page 모임 상세페이지 UI 개발
  app/meeting-detail/[meetingsId]/_components/BookInfo.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailLeft.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailRight.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailTabs.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingInfo.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingReviews.tsx
  app/meeting-detail/[meetingsId]/page.tsx
  components/ui/progress.tsx
  package-lock.json
  package.json
  public/Avatar.tsx
  public/BookIcon.tsx
  public/BookOpenIcon.tsx
  public/CalendarDotIcon.tsx
  public/ChevronDownIcon.tsx
  public/HeartIcon.tsx
  public/ShareIcon.tsx
  public/StarBlank.tsx
  public/StarFill.tsx
  public/UserIcon.tsx
  public/UsersIcon.tsx
  public/calendar-dot.png
  public/dropdownIcon.tsx
  public/heart.png
Labels: 디자인 🎨

#64 Feat/mainpage api 모임 목록 페이지 body파트 api연결 완료
  app/_components/MainPageBody.tsx
  app/_services/fetchMeetings.ts
  app/_services/popularBooks.ts
  app/_services/useMeetingsInfiniteQuery.ts
  app/page.tsx
  app/types/index.ts
  next.config.js
  public/BookIcon.tsx
  public/CalendarDotIcon.tsx
  public/CalendarIcon.tsx
  public/ChevronDown.tsx
  public/DropdownIcon.tsx
  public/RotateCw.tsx
  public/SearchIcon.tsx
  public/UsersIcon.tsx
Labels: 기능 🔧

#69 hotfix: 이미지 컴포넌트 코드 통일, props타입 통일, 배포오류 원인 수정 (#68)
  app/_components/MainPageBody.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailLeft.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailRight.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingInfo.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingReviews.tsx
  public/AvatarIcon.tsx
  public/BookOpenIcon.tsx
  public/ChevronDown.tsx
  public/ChevronDownIcon.tsx
  public/HeartIcon.tsx
  public/RotateCwIcon.tsx
  public/ShareIcon.tsx
  public/StarBlankIcon.tsx
  public/StarFillIcon.tsx
  public/UserIcon.tsx
  public/calendar-dot.png
Labels: 오류 수정 ✔️

#71 Feat/review 리뷰 페이지 Best 리뷰와 작성하지 않은 리뷰 조회하기
  app/mypage/_components/MyMeetingList.tsx
  app/mypage/_components/MyReadingCalendar.tsx
  app/mypage/_components/Profile.tsx
  app/mypage/_components/ProfileModifyForm.tsx
  app/mypage/meetings/_components/Meeting.tsx
  app/mypage/meetings/_components/Pagination.tsx
  app/reviews/[id]/page.tsx
  app/reviews/_components/BestReviewCard.tsx
  app/reviews/_components/BestReviews.tsx
  app/reviews/_components/PendingReviewBox.tsx
  app/reviews/_components/ReviewDashboard.tsx
  app/reviews/_components/UserInfo.tsx
  app/reviews/_lib/getBestAndPendingReviews.ts
  app/reviews/_lib/getBestAndPendingReviewsServer.ts
  app/reviews/_svg/BookIcon.tsx
  app/reviews/_svg/CommentIcon.tsx
  app/reviews/_svg/LikeIcon.tsx
  app/reviews/edit/[id]/page.tsx
  app/reviews/page.tsx
  app/reviews/write/page.tsx
  components/Modal.tsx
  components/common/icons/Avatar.tsx
  components/common/icons/CloseIcon.tsx
  components/common/icons/MoreIcon.tsx
  components/common/icons/PageNext.tsx
  components/common/icons/PagePrev.tsx
  components/common/icons/SlideNextIcon.tsx
  components/common/icons/SlidePrevIcon.tsx
  types/book.ts
Labels: 기능 🔧

#70 Feat,style/signup
  app/auth/_components/form-input-field.tsx
  app/auth/_svg/CheckIcon.tsx
  app/auth/_svg/EyeIconClosed.tsx
  app/auth/_svg/XIcon.tsx
  app/auth/login/_lib/login.ts
  app/auth/signup/_components/signup-form-duplicateCheckButton.tsx
  app/auth/signup/_components/signup-form-input.tsx
  app/auth/signup/_components/signup-form.tsx
  app/auth/signup/_lib/duplicate-check.ts
  app/auth/signup/_lib/signup-validation.ts
  app/auth/signup/_lib/signup.ts
Labels: 기능 🔧, 디자인 🎨, 오류 수정 ✔️

#74 Feat/detailpage api header 모임 상세페이지 헤더파트 api연결 및 기능구현
  app/_components/MainPageBody.tsx
  app/meeting-detail/[meetingsId]/_components/BookInfo.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailLeft.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailRight.tsx
  app/meeting-detail/[meetingsId]/_lib/MeetingDetailContext.tsx
  app/meeting-detail/[meetingsId]/_lib/meetingDetail.ts
  app/meeting-detail/[meetingsId]/_utils/calculateEndDate.ts
  app/meeting-detail/[meetingsId]/_utils/calculateRemainDays.ts
  app/meeting-detail/[meetingsId]/page.tsx
  app/types/index.ts
Labels: 기능 🔧

#76 Feat/detailpage api header 모임 상세페이지 헤더파트 코드 수정 및 업데이트
  app/meeting-detail/[meetingsId]/_components/MeetingDetailLeft.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailRight.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingsDetails.tsx
  app/meeting-detail/[meetingsId]/_lib/MeetingDetailContext.tsx
  app/meeting-detail/[meetingsId]/_lib/meetingDetail.ts
  app/meeting-detail/[meetingsId]/page.tsx
  app/types/index.ts
Labels: 기능 🔧, 리팩토링 ⚙️

#77 Feat/review-filter 독서 리뷰 필터링 검색 무한 스크롤 적용
  app/reviews/_components/BestReviews.tsx
  app/reviews/_components/Filter.tsx
  app/reviews/_components/PendingReviewBox.tsx
  app/reviews/_components/Review.tsx
  app/reviews/_components/ReviewDashboard.tsx
  app/reviews/_components/ReviewList.tsx
  app/reviews/_lib/getFilteredBookReviews.ts
  app/reviews/_lib/getFilteredBookReviewsServer.ts
  app/reviews/_svg/DropDownThinIcon.tsx
  app/reviews/_svg/DropUpThinIcon.tsx
  app/reviews/page.tsx
  components/InfiniteScroll.tsx
  hooks/useReviewsInfinityQuery.ts
  types/book.ts
  types/review.ts
Labels: 기능 🔧, 오류 수정 ✔️

#78 Style/login 로그인 페이지와 회원가입 페이지 스타일 적용 및 리팩토링
  app/auth/login/_components/login-form-input-field.tsx
  app/auth/login/_components/login-form-input.tsx
  app/auth/login/_components/login-form.tsx
  app/auth/login/_lib/login.ts
  app/auth/login/page.tsx
  app/auth/signup/_components/TermsAgreement.tsx
  app/auth/signup/_components/signup-form-input-field.tsx
  app/auth/signup/_components/signup-form-input.tsx
  app/auth/signup/_components/signup-form.tsx
Labels: 디자인 🎨, 리팩토링 ⚙️

#79 feat: 모임상세페이지 > 모임소개 탭 API연결 (#66)
  app/meeting-detail/[meetingsId]/_components/MeetingDetailTabs.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingInfo.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingsDetails.tsx
  app/meeting-detail/[meetingsId]/_lib/meetingDetail.ts
  app/types/index.ts
  public/AvatarIcon.tsx
  public/ClosedBookIcon.tsx
Labels: 기능 🔧

#80 Feat/review-filter 리뷰 좋아요 기능 구현
  app/reviews/_components/BestReviewCard.tsx
  app/reviews/_components/Filter.tsx
  app/reviews/_components/Review.tsx
  app/reviews/_components/ReviewList.tsx
  app/reviews/_lib/getBestAndPendingReviews.ts
  app/reviews/_lib/getFilteredBookReviews.ts
  app/reviews/_lib/getFilteredBookReviewsServer.ts
  app/reviews/_lib/toggleReviewLike.ts
  app/reviews/page.tsx
  hooks/useReviewLikeQuery.ts
  hooks/useReviewsInfinityQuery.ts
  tailwind.config.ts
  types/book.ts
Labels: 기능 🔧, 디자인 🎨, 오류 수정 ✔️

#83 Feat/gnb 글로벌 네이게이션 바 기능 구현
  app/auth/login/_components/login-form.tsx
  app/auth/login/_lib/login.ts
  app/auth/login/page.tsx
  app/auth/signup/_components/signup-form.tsx
  app/auth/signup/page.tsx
  app/layout.tsx
  components/GNB.tsx
  components/common/icons/BellIcon.tsx
  components/common/icons/HeartIcon.tsx
  components/common/icons/SearchIcon.tsx
  components/ui/skeleton.tsx
  public/AvatarIcon.tsx
  public/Logo.tsx
  public/UserIcon.tsx
  public/file.svg
  public/globe.svg
  public/window.svg
  tailwind.config.ts
Labels: 기능 🔧, 디자인 🎨, 리팩토링 ⚙️

#84 Refactor/review 리뷰 페이지 리팩토링
  app/reviews/_components/BestReviewCard.tsx
  app/reviews/_components/BestReviews.tsx
  app/reviews/_components/Filter.tsx
  app/reviews/_components/NoPendingReviewBox.tsx
  app/reviews/_components/PendingReviewBox.tsx
  app/reviews/_components/UserInfo.tsx
  app/reviews/_svg/CommentIcon.tsx
  app/reviews/_svg/LikeIcon.tsx
  hooks/useReviewQuery.ts
Labels: 디자인 🎨, 리팩토링 ⚙️

#88 Fix/calendar 달력 커스텀 스타일 중복 오류 해결
  app/mypage/_components/CustomReadingCalendar.css
  app/mypage/_components/MyReadingCalendar.tsx
  app/mypage/page.tsx
Labels: 디자인 🎨, 오류 수정 ✔️

#92 Feat/login,logout 로그인후 전역적으로 유저정보 관리 추가 및 로그아웃 기능 추가 및 적용
  app/_utils/logout.ts
  app/auth/login/_components/login-form.tsx
  app/auth/login/_lib/login.ts
  app/mypage/_components/Sidebar.tsx
  components/GNB.tsx
  store/userStore.ts
Labels: 기능 🔧, 리팩토링 ⚙️

#93 Feat/review-detail 리뷰 상세 페이지 정보 불러오기
  app/mypage/meetings/_components/MeetingList.tsx
  app/reviews/[id]/_components/BookReviewList.tsx
  app/reviews/[id]/_components/CommentList.tsx
  app/reviews/[id]/_components/ReviewCard.tsx
  app/reviews/[id]/_components/ReviewDetail.tsx
  app/reviews/[id]/_components/ReviewTag.tsx
  app/reviews/[id]/_lib/getBookReviews.ts
  app/reviews/[id]/_lib/getBookReviewsServer.ts
  app/reviews/[id]/_lib/getReviewDetail.ts
  app/reviews/[id]/_lib/getReviewDetailServer.ts
  app/reviews/[id]/page.tsx
  components/Pagination.tsx
  components/common/icons/MoreIcon.tsx
  hooks/useReviewLikeQuery.ts
  types/book.ts
  types/review.ts
Labels: 기능 🔧, 디자인 🎨

#95 Feat/review-detail 리뷰 상세페이지 리팩토링
  app/reviews/[id]/_components/CommentInput.tsx
  app/reviews/[id]/_components/CommentList.tsx
  app/reviews/[id]/_components/GatheringAction.tsx
  app/reviews/[id]/_components/ReviewCard.tsx
  app/reviews/[id]/_components/ReviewDetail.tsx
  app/reviews/_components/BestReviewCard.tsx
  app/reviews/_components/Review.tsx
  components/Pagination.tsx
  hooks/useReviewLikeQuery.ts
Labels: 디자인 🎨, 리팩토링 ⚙️, 오류 수정 ✔️

#97 Style/login,signup 로그인페이지 회원가입페이지 GNB 스타일 변경 적용
  app/auth/login/_components/login-form-input-field.tsx
  app/auth/login/_components/login-form-input.tsx
  app/auth/login/_components/login-form.tsx
  app/auth/login/page.tsx
  app/auth/signup/_components/TermsAgreement.tsx
  app/auth/signup/_components/signup-form-input-field.tsx
  app/auth/signup/_components/signup-form-input.tsx
  app/auth/signup/_components/signup-form.tsx
  components/GNB.tsx
Labels: 디자인 🎨

#98 Feat/detailpage api header 모임 상세페이지 헤더파트 api 연결 및 기능 구현
  app/_components/MainPageBody.tsx
  app/_utils/dateFormatter.ts
  app/meeting-detail/[meetingsId]/_components/BookInfo.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailLeft.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailRight.tsx
  app/meeting-detail/[meetingsId]/_lib/meetingDetail.ts
  app/types/index.ts
  package-lock.json
  package.json
Labels: 기능 🔧

#99 Feat/review-detail-crud 리뷰 삭제, 댓글 추가/수정/삭제 작업 완료
  app/_utils/dateFormatter.ts
  app/reviews/[id]/_components/BookReviewList.tsx
  app/reviews/[id]/_components/CommentInput.tsx
  app/reviews/[id]/_components/CommentItem.tsx
  app/reviews/[id]/_components/CommentList.tsx
  app/reviews/[id]/_components/ConfirmModal.tsx
  app/reviews/[id]/_components/DropDown.tsx
  app/reviews/[id]/_components/ReviewDetail.tsx
  app/reviews/[id]/_lib/comment.ts
  app/reviews/[id]/_lib/deleteBookReview.ts
  app/reviews/_components/BestReviews.tsx
  app/reviews/_components/PendingReviewBox.tsx
  app/reviews/_components/Review.tsx
  components/Modal.tsx
  hooks/useBestReviewQuery.ts
  hooks/useReviewCommentQuery.ts
  hooks/useReviewQuery.ts
Labels: 기능 🔧, 리팩토링 ⚙️, 오류 수정 ✔️

#103 Style/detailpage UI 모임 상세 페이지 UI 업데이트
  app/_utils/dateFormatter.ts
  app/meeting-detail/[meetingsId]/_components/BookInfo.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailLeft.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailRight.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailTabs.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingInfo.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingReviews.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingsDetails.tsx
  app/meeting-detail/[meetingsId]/_lib/meetingDetail.ts
  components/ui/tooltip.tsx
  package-lock.json
  package.json
Labels: 디자인 🎨

#104 Feat/detailpage api 모임 상세페이지 UI, 기능 업데이트 반영
  app/_components/MainPageBody.tsx
  app/_utils/dateFormatter.ts
  app/meeting-detail/[meetingsId]/_components/BookInfo.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailLeft.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailRight.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingDetailTabs.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingInfo.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingReviews.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingsDetails.tsx
  app/meeting-detail/[meetingsId]/_components/PageLocator.tsx
  app/meeting-detail/[meetingsId]/_lib/meetingDetail.ts
  app/meeting-detail/[meetingsId]/_utils/calculateEndDate.ts
  app/meeting-detail/[meetingsId]/_utils/calculateRemainDays.ts
  app/meeting-detail/[meetingsId]/page.tsx
  app/types/index.ts
  components/ui/tooltip.tsx
  package-lock.json
  package.json
  public/AvatarIcon.tsx
  public/BookIcon.tsx
  public/ChevronRight.tsx
  public/ChevronUpIcon.tsx
  public/ClosedBookIcon.tsx
  public/HomeIcon.tsx
  public/InfoIcon.tsx
  public/MeetingOwnerIcon.tsx
  public/StarFillIcon.tsx
Labels: 기능 🔧, 디자인 🎨, 리팩토링 ⚙️

#106 Fix/bookmark meeting 모임 찜하기 기능 오류 수정
  app/meeting-detail/[meetingsId]/_components/MeetingDetailLeft.tsx
  app/meeting-detail/[meetingsId]/_lib/meetingDetail.ts
  components/ui/alert-dialog.tsx
  package-lock.json
  package.json
Labels: 기능 🔧, 오류 수정 ✔️

#110 Hotfix/build error 빌드시 발생하는 오류를 해결
  app/meeting-detail/[meetingsId]/_components/BookInfo.tsx
  app/reviews/[id]/_components/DropDown.tsx
Labels: 오류 수정 ✔️

#111 Feat/searchpage 검색 페이지 구현, GNB를 api의존에서 store 의존으로 변경, middleware 로그인안되어있는 상태에서 이동되는 페이지를 /login 에서 /auth/login으로 변경
  app/auth/login/_components/login-form-input-field.tsx
  app/auth/login/_components/login-form.tsx
  app/auth/signup/_lib/duplicate-check.ts
  app/search/[searchWord]/page.tsx
  app/search/page.tsx
  components/GNB.tsx
  components/common/icons/InputReset.tsx
  components/common/icons/PageNext.tsx
  components/common/icons/PagePrev.tsx
  components/ui/SearchBar.tsx
  middleware.ts
  public/ChevronDownIcon.tsx
Labels: 기능 🔧, 디자인 🎨, 리팩토링 ⚙️

#113 Feat/review-create 리뷰 작성/수정 기능
  app/globals.css
  app/reviews/[id]/_components/CommentList.tsx
  app/reviews/[id]/_components/DropDown.tsx
  app/reviews/[id]/_components/ReviewDetail.tsx
  app/reviews/[id]/edit/_components/ReviewEditForm.tsx
  app/reviews/[id]/edit/_lib/updateBookReview.ts
  app/reviews/[id]/edit/page.tsx
  app/reviews/_components/BookContext.tsx
  app/reviews/_lib/getMyMeetingBooks.ts
  app/reviews/_lib/reviewSchema.ts
  app/reviews/_lib/searchBookByName.ts
  app/reviews/edit/[id]/page.tsx
  app/reviews/write/_components/BookFeedback.tsx
  app/reviews/write/_components/BookInfo.tsx
  app/reviews/write/_components/BookSearchModal.tsx
  app/reviews/write/_components/BookSelector.tsx
  app/reviews/write/_components/Message.tsx
  app/reviews/write/_components/PopularKeyword.tsx
  app/reviews/write/_components/ReadOnlyBookTitle.tsx
  app/reviews/write/_components/ReviewForm.tsx
  app/reviews/write/_lib/createBookReview.ts
  app/reviews/write/_lib/getPopularKeyword.ts
  app/reviews/write/_svg/PlusIcon.tsx
  app/reviews/write/_svg/ThinCheckIcon.tsx
  app/reviews/write/page.tsx
  components/Modal.tsx
  components/common/icons/CloseIcon.tsx
  hooks/useReveiwDetailQuery.ts
  hooks/useReviewQuery.ts
  middleware.ts
  package-lock.json
  package.json
  types/book.ts
Labels: 기능 🔧, 디자인 🎨, 오류 수정 ✔️, 최적화 🌠
