Repository Codeit-Sprint-Teamproject/frontend, pull requests merged in 2025-01, with the labels that each got.

#115 Feat/review-improve 리뷰 페이지 필요한 부분 수정
  app/_utils/dateFormatter.ts
  app/reviews/[id]/_components/BookReviewList.tsx
  app/reviews/[id]/_components/CommentInput.tsx
  app/reviews/[id]/_components/CommentItem.tsx
  app/reviews/[id]/_components/ReviewCard.tsx
  app/reviews/[id]/_components/ReviewDetail.tsx
  app/reviews/_components/BestReviewCard.tsx
  app/reviews/_components/PendingReviewBox.tsx
  app/reviews/_components/Review.tsx
  app/reviews/_components/ReviewDashboard.tsx
  app/reviews/_components/ReviewList.tsx
  app/reviews/_components/UserInfo.tsx
  app/reviews/_svg/LikeIcon.tsx
  app/reviews/_svg/UnLikeIcon.tsx
  app/reviews/queries.ts
  app/reviews/write/_components/BookInfo.tsx
  components/common/icons/SlideNextIcon.tsx
  hooks/useReviewLikeQuery.ts
  hooks/useReviewLikeToggle.ts
  tailwind.config.ts
  types/book.ts
Labels: 기능 🔧, 디자인 🎨, 리팩토링 ⚙️

#120 Feat/review-improve 리뷰 메인 페이지 스타일 변경
  app/reviews/_components/BestReviewCard.tsx
  app/reviews/_components/BestReviews.tsx
  app/reviews/_components/Filter.tsx
  app/reviews/_components/NoPendingReviewBox.tsx
  app/reviews/_components/PendingReviewBox.tsx
  app/reviews/_components/ReviewDashboard.tsx
  app/reviews/_components/UserInfo.tsx
  app/reviews/_svg/BookIcon.tsx
  public/book.png
Labels: 디자인 🎨

#122 Feat/create gathering 모임 생성 페이지 구
  app/create-gathering/_components/BookSearchDialog.tsx
  app/create-gathering/_components/GatheringForm.tsx
  app/create-gathering/_components/StarRating.tsx
  app/create-gathering/page.tsx
  components/GNB.tsx
  components/common/icons/AddImage.tsx
  components/common/icons/Star.tsx
  components/ui/dialog.tsx
  package-lock.json
  package.json
Labels: 기능 🔧, 디자인 🎨, 리팩토링 ⚙️

#125 Style/search#2 검색페이지 리팩토링 및 스타일
  app/search/[searchWord]/page.tsx
  app/search/page.tsx
  components/common/icons/Book.tsx
  components/common/icons/Calendar.tsx
  components/common/icons/Comment.tsx
  components/common/icons/Like.tsx
  components/common/icons/Participants.tsx
  components/common/icons/ReadingTIme.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: 디자인 🎨, 리팩토링 ⚙️

#126 Feat/profile 프로필 조회 및 수정
  app/mypage/_components/MyMeetingList.tsx
  app/mypage/_components/Profile.tsx
  app/mypage/_components/ProfileModifyForm.tsx
  app/mypage/_lib/getActiveMeetings.ts
  app/mypage/_lib/getProfile.ts
  app/mypage/_svg/EditIcon.tsx
  app/mypage/page.tsx
  app/mypage/profile/edit/_components/NicknameInput.tsx
  app/mypage/profile/edit/_components/PasswordEditForm.tsx
  app/mypage/profile/edit/_components/PasswordInput.tsx
  app/mypage/profile/edit/_components/ProfileImageUploader.tsx
  app/mypage/profile/edit/_components/ProfileModifyForm.tsx
  app/mypage/profile/edit/_lib/checkCurrentPassword.ts
  app/mypage/profile/edit/_lib/updateProfile.ts
  app/mypage/profile/edit/_svg/CameraIcon.tsx
  app/mypage/profile/edit/page.tsx
  hooks/userProfileQuery.ts
  types/user.ts
Labels: 기능 🔧, 디자인 🎨, 오류 수정 ✔️

#128 Feat/active-meeting 독서 완료와 모임 나가기 기능
  app/mypage/_components/CustomReadingCalendar.css
  app/mypage/_components/MyReadingCalendar.tsx
  app/mypage/_lib/getReadingCalendar.ts
  app/mypage/meetings/_components/AlertModal.tsx
  app/mypage/meetings/_components/Meeting.tsx
  app/mypage/meetings/_components/MeetingList.tsx
  app/mypage/meetings/_components/Tab.tsx
  app/mypage/meetings/_lib/completeReading.ts
  app/mypage/meetings/_lib/leaveMeeting.ts
  app/mypage/meetings/page.tsx
  app/reviews/[id]/_components/CommentItem.tsx
  app/reviews/[id]/_components/DropDown.tsx
  app/reviews/[id]/_components/ReviewDetail.tsx
  components/ConfirmModal.tsx
  components/DropDown.tsx
  components/Modal.tsx
  components/Pagination.tsx
  types/book.ts
  types/meeting.ts
Labels: 기능 🔧, 디자인 🎨, 리팩토링 ⚙️

#129 Feat,style/mainpage body 메인페이지 바디파트 UI, 일부기능 구현완료
  app/_components/MainPageBody.tsx
  app/_components/MainPageHeader.tsx
  app/_components/_lib/getPopularBooks.ts
  app/_svg/BookIcon.tsx
  app/_svg/BookRankIcon.tsx
  app/_svg/DurationIcon.tsx
  app/_svg/PopularBooksIcon.tsx
  app/_svg/SearchIcon.tsx
  components/ui/switch.tsx
Labels: 기능 🔧, 디자인 🎨

#130 Feat/profile 프로필 작업 마무리
  app/mypage/_components/Sidebar.tsx
  app/mypage/layout.tsx
  app/mypage/page.tsx
  app/mypage/profile/edit/_components/NicknameInput.tsx
Labels: 기능 🔧, 디자인 🎨

#132 Feat/active-meeting 참여중인 모임 UI 일부 수정
  app/globals.css
  app/mypage/meetings/_components/EmptyMeetingList.tsx
  app/mypage/meetings/_components/Meeting.tsx
  app/mypage/meetings/_components/MeetingDropDown.tsx
  app/mypage/meetings/_components/MeetingList.tsx
  app/mypage/meetings/_lib/mymeetings.ts
  types/meeting.ts
Labels: 기능 🔧, 리팩토링 ⚙️, 오류 수정 ✔️

#134 Feat/manage-meeting 내가 만든 모임 삭제와 찜하기 해제 기능
  app/mypage/meetings/_components/Meeting.tsx
  app/mypage/meetings/_components/MeetingDropDown.tsx
  app/mypage/meetings/_lib/deleteMeeting.ts
  app/mypage/meetings/_lib/mymeetings.ts
  app/mypage/meetings/_lib/unlikeMeeting.ts
Labels: 기능 🔧, 디자인 🎨, 오류 수정 ✔️

#136 hotfix: 모임상세페이지 api 업데이트 (#135)
  app/_components/custom-calendar.css
  app/_svg/BookIcon.tsx
  app/meeting-detail/[meetingsId]/_components/MeetingInfo.tsx
  app/meeting-detail/[meetingsId]/_lib/meetingDetail.ts
  components/common/icons/Book.tsx
  components/common/icons/Comment.tsx
  public/MeetingOwnerIcon.tsx
Labels: 기능 🔧, 오류 수정 ✔️

#139 fix: fetchAPIClient 주소값 변경
  lib/fetchAPI.client.ts
Labels: bug

#142 Feat/my-review 나의 리뷰 페이지 작업
  app/mypage/reviews/_components/Review.tsx
  app/mypage/reviews/_components/ReviewList.tsx
  app/mypage/reviews/_lib/getMyReview.ts
  app/mypage/reviews/page.tsx
  app/reviews/[id]/_components/ReviewCard.tsx
  app/reviews/_components/BestReviewCard.tsx
  app/reviews/_components/Review.tsx
  components/common/icons/Book.tsx
  types/review.ts
Labels: 기능 🔧

#144 Fix/my-meeting 참여중인 모임 조회 요청 주소 변경
  app/mypage/meetings/_lib/mymeetings.ts
Labels: 오류 수정 ✔️

#147 Style/mypage 마이페이지 나의 모임 리스트 UI 수정
  app/mypage/_components/MyMeetingList.tsx
  app/mypage/meetings/_components/Meeting.tsx
  app/mypage/page.tsx
Labels: 디자인 🎨
